### PR TITLE
change getValue() to value for input field

### PR DESCRIPTION
**Pull request by kevohagan**

### CODE REVIEW

**Comment by djhi** [comment]
Can you explain ?

**Comment by kevohagan** [comment]
yeah sorry. in the mealtime component, getting the value of the input field for time does not work with getValue(). rather with ``  this.refs.time.value; ``

**Comment by djhi** [comment]
Ok, should I close this then ?

**Comment by djhi** [comment]
Misread your explanation... I'll check more carefully asap. Thanks

**Comment by kevohagan** [comment]
This is a pull request :), do whatever you please with it ;)

**Pull request merged**
